#!/usr/bin/env python3
"""
snEco — D1 Ingest (added v2.50)
Reads xlsx files generated by moysklad_sync.py and POSTs batches to
Cloudflare Worker /api/dashboard/ingest, which writes to D1 (sneco-bible).

Usage:
  python3 ingest_to_d1.py
  python3 ingest_to_d1.py --data-dir ./data --worker https://sneco-auth.vg-ab6.workers.dev

Env (required):
  WORKER_URL          base URL of sneco-auth Worker (e.g. https://sneco-auth.vg-ab6.workers.dev)
  SYNC_API_KEY        secret matching env.SYNC_API_KEY in the Worker

Reads xlsx from ./data/ (or --data-dir):
  demands.xlsx · payments.xlsx · customer_orders.xlsx · salesreturns.xlsx
  products.xlsx · counterparties.xlsx · invoices_out.xlsx · moves.xlsx · processing_plans.xlsx

Posts a final ms_sync_log row at the end.
"""

import os, sys, json, time, math, argparse, traceback
from pathlib import Path
from datetime import datetime, timezone

try:
    import pandas as pd
    import requests
except ImportError:
    print("Install deps: pip install pandas openpyxl requests")
    sys.exit(1)

try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).parent / ".env")
except ImportError:
    pass

BATCH_SIZE = 50   # Зменшили з 400 → 50 (v2.63) щоб уникнути CF Worker payload/D1 batch limits

# Колонки що мають INTEGER kopecks у D1 але приходять як float грн у xlsx (moysklad_sync.py / 100).
# При ingest множимо ×100 щоб повернути назад у копійки.
KOP_COLS = {
    "sum_kop", "payed_sum_kop", "shipped_sum_kop",
    "sale_price_kop", "buy_price_kop", "min_price_kop",
    "balance_kop", "overdue_debt_kop",  # v2.67
    "price_kop",                         # v2.70: для ms_demand_positions
}

# Map xlsx file → entity slug + column rename map (xlsx header → D1 column).
# moysklad_sync.py пише UA заголовки (Дата, Номер, Контрагент, Сума грн, etc.) — мапимо їх первими.
# EN aliases лишаються як fallback для backwards-compat / Pylyp local script.
ENTITY_MAP = {
    "demands": {
        "file": "demands.xlsx",
        "cols": {
            # UA (real headers from moysklad_sync.parse_demands) ─────────
            "Дата": "ms_moment",
            "Номер": "name",
            "Контрагент": "agent",
            "Контрагент ID": "agent_id",
            "Організація": "organization",
            "Склад": "store",
            "Сума, грн": "sum_kop",
            "Оплачено, грн": "payed_sum_kop",
            "Стан": "state",
            # EN aliases (fallback) ─────────────────────────────────────
            "id": "id",
            "moment": "ms_moment",
            "name": "name",
            "sum": "sum_kop",
            "organization_name": "organization", "organization": "organization",
            "agent_name": "agent", "agent": "agent",
            "store_name": "store", "store": "store",
            "contract_name": "contract", "contract": "contract",
            "state_name": "state", "state": "state",
            "applicable": "applicable",
            "vatIncluded": "vat_included", "vat_included": "vat_included",
            "vatEnabled": "vat_enabled", "vat_enabled": "vat_enabled",
            "payedSum": "payed_sum_kop", "payed_sum": "payed_sum_kop",
        },
    },
    "payments": {
        "file": "payments.xlsx",
        "cols": {
            # UA (real) ─────────
            "Дата": "ms_moment",
            "Номер": "name",
            "Тип": "payment_type",
            "Контрагент": "agent",
            "Контрагент ID": "agent_id",
            "Організація": "organization",
            "Сума, грн": "sum_kop",
            # EN aliases ─────────
            "id": "id",
            "moment": "ms_moment",
            "type": "payment_type", "payment_type": "payment_type",
            "name": "name",
            "sum": "sum_kop",
            "organization_name": "organization", "organization": "organization",
            "agent_name": "agent", "agent": "agent",
            "account_name": "account", "account": "account",
            "expenseItem_name": "expense_item", "expenseItem": "expense_item",
        },
    },
    "orders": {
        "file": "customer_orders.xlsx",
        "cols": {
            # UA (real) ─────────
            "Дата": "ms_moment",
            "Номер": "name",
            "Контрагент": "agent",
            "Контрагент ID": "agent_id",
            "Організація": "organization",
            "Сума, грн": "sum_kop",
            "Оплачено, грн": "payed_sum_kop",
            "Відвантажено, грн": "shipped_sum_kop",
            "Стан": "state",
            # EN aliases ─────────
            "id": "id",
            "moment": "ms_moment",
            "name": "name",
            "sum": "sum_kop",
            "shippedSum": "shipped_sum_kop", "shipped_sum": "shipped_sum_kop",
            "payedSum": "payed_sum_kop", "payed_sum": "payed_sum_kop",
            "organization_name": "organization", "organization": "organization",
            "agent_name": "agent", "agent": "agent",
            "store_name": "store", "store": "store",
            "contract_name": "contract", "contract": "contract",
            "state_name": "state", "state": "state",
            "deliveryPlannedMoment": "delivery_planned_moment",
        },
    },
    "returns": {
        # FIXED: moysklad_sync.py writes sales_returns.xlsx (з underscore, було salesreturns.xlsx)
        "file": "sales_returns.xlsx",
        "cols": {
            # UA (real) ─────────
            "Дата": "ms_moment",
            "Номер": "name",
            "Контрагент": "agent",
            "Контрагент ID": "agent_id",
            "Склад": "store",
            "Сума, грн": "sum_kop",
            # EN aliases ─────────
            "id": "id",
            "moment": "ms_moment",
            "name": "name",
            "sum": "sum_kop",
            "organization_name": "organization", "organization": "organization",
            "agent_name": "agent", "agent": "agent",
            "store_name": "store", "store": "store",
            "demand_id": "demand_id",
        },
    },
    "products": {
        "file": "products.xlsx",
        "cols": {
            # UA (real) ─────────
            "Назва": "name",
            "Код": "code",
            "Артикул": "article",
            "Штрихкод": "ean_codes",
            "Група": "product_folder",
            "Одиниця": "uom",
            "Ціна продажу": "sale_price_kop",
            "Ціна закупки": "buy_price_kop",
            "Архів": "archived",
            # EN aliases ─────────
            "id": "id",
            "name": "name",
            "code": "code",
            "externalCode": "external_code", "external_code": "external_code",
            "article": "article",
            "uom_name": "uom", "uom": "uom",
            "weight": "weight_g",
            "volume": "volume_ml",
            "salePrices_value": "sale_price_kop", "sale_price": "sale_price_kop",
            "buyPrice_value": "buy_price_kop", "buy_price": "buy_price_kop",
            "minPrice_value": "min_price_kop", "min_price": "min_price_kop",
            "productFolder_name": "product_folder", "product_folder": "product_folder",
            "archived": "archived",
            "barcodes": "ean_codes",
        },
    },
    "counterparties": {
        "file": "counterparties.xlsx",
        "cols": {
            # UA (real headers from moysklad_sync) ─────────
            "Назва": "name",
            "Повна назва": "full_name",                    # NEW v2.67
            "Тип": "company_type",
            "Код": "code",
            "ЄДРПОУ/ІНН": "inn",
            "Телефон": "phone",
            "Факс": "fax",                                  # NEW v2.67
            "Email": "email",
            "Юр.адреса": "legal_address",                  # NEW v2.67
            "Юр.адреса коментар": "legal_address_comment", # NEW v2.67
            "Факт.адреса": "actual_address",                # NEW v2.67
            "Теги": "tags",
            "Баланс, грн": "balance_kop",                   # NEW v2.67 (KOP conversion)
            "Борг прострочений": "overdue_debt_kop",        # NEW v2.67 (KOP conversion)
            "Статус": "state",                              # NEW v2.67
            "Коментар": "description",                      # NEW v2.67
            # EN aliases ─────────
            "id": "id",
            "name": "name",
            "code": "code",
            "externalCode": "external_code", "external_code": "external_code",
            "inn": "inn",
            "edrpou": "edrpou",
            "legalAddress": "legal_address", "legal_address": "legal_address",
            "actualAddress": "actual_address", "actual_address": "actual_address",
            "email": "email",
            "phone": "phone",
            "fax": "fax",
            "tags": "tags",
            "companyType": "company_type", "company_type": "company_type",
            "archived": "archived",
            "description": "description",
            "balance": "balance_kop",
            "overdueDebt": "overdue_debt_kop",
        },
    },
    "invoices_out": {
        "file": "invoices_out.xlsx",
        "cols": {
            # UA (real) ─────────
            "Дата": "ms_moment",
            "Номер": "name",
            "Контрагент": "agent",
            "Контрагент ID": "agent_id",
            "Сума, грн": "sum_kop",
            "Оплачено, грн": "payed_sum_kop",
            "Стан": "state",
            "Очікувана оплата": "payment_planned_moment",
            # EN aliases ─────────
            "id": "id",
            "moment": "ms_moment",
            "name": "name",
            "sum": "sum_kop",
            "organization_name": "organization", "organization": "organization",
            "agent_name": "agent", "agent": "agent",
            "paymentPlannedMoment": "payment_planned_moment",
            "payedSum": "payed_sum_kop", "payed_sum": "payed_sum_kop",
            "state_name": "state", "state": "state",
        },
    },
    "moves": {
        "file": "moves.xlsx",
        "cols": {
            # UA (real) ─────────
            "Дата": "ms_moment",
            "Номер": "name",
            "Зі складу": "source_store",
            "На склад": "target_store",
            # EN aliases ─────────
            "id": "id",
            "moment": "ms_moment",
            "name": "name",
            "sourceStore_name": "source_store", "source_store": "source_store",
            "targetStore_name": "target_store", "target_store": "target_store",
            "organization_name": "organization", "organization": "organization",
        },
    },
    "processing_plans": {
        "file": "processing_plans.xlsx",
        "cols": {
            # UA (real) ─────────
            "Назва": "name",
            "Код": "code",
            "Продукт": "parent_product",
            # EN aliases ─────────
            "id": "id",
            "name": "name",
            "code": "code",
            "parentProduct_id": "parent_product", "parent_product": "parent_product",
            "archived": "archived",
        },
    },
    # v2.70: окрема таблиця позицій з відвантажень — для ТОП-10 продуктів у Customer 360.
    # ВАЖЛИВО: тут НЕМАЄ поля 'id' — primary key composite (demand_id, position_idx).
    # df_to_rows() використовує d.get('id'); для positions ми ставимо id == demand_id + ':' + idx.
    "demand_positions": {
        "file": "demand_positions.xlsx",
        "cols": {
            # UA (real) ─────────
            "demand_id":       "demand_id",
            "position_idx":    "position_idx",
            "Товар":           "product_name",
            "Товар ID":        "product_id",
            "Кількість":       "quantity",
            "Ціна, грн":       "price_kop",       # KOP × 100
            "Сума, грн":       "sum_kop",         # KOP × 100
            "Знижка %":        "discount_pct",
            "Контрагент ID":   "agent_id",
            "Контрагент":      "agent",
            "Дата":            "ms_moment",
        },
    },
}


def normalise_value(v):
    """Convert pandas/numpy → JSON-safe Python."""
    if v is None: return None
    if isinstance(v, float) and (math.isnan(v) or math.isinf(v)): return None
    if hasattr(v, 'isoformat'): return v.isoformat()  # datetime
    if hasattr(v, 'item'): return v.item()  # numpy scalar
    if isinstance(v, bool): return 1 if v else 0
    return v


def df_to_rows(df: pd.DataFrame, col_map: dict) -> list:
    """Convert DataFrame rows → list of dicts using col_map (xlsx_col → d1_col).
    Для колонок у KOP_COLS значення множиться ×100 (грн → копійки) щоб відповідати INTEGER schema D1."""
    out = []
    for _, row in df.iterrows():
        d = {}
        raw = {}
        for col in df.columns:
            v = normalise_value(row[col])
            raw[str(col)] = v
            if col in col_map:
                target = col_map[col]
                # First mapping wins (col_map may have aliases)
                if target not in d or d[target] is None:
                    # KOP conversion: source value у грн (float), target INTEGER kopecks
                    if target in KOP_COLS and isinstance(v, (int, float)):
                        try:
                            d[target] = int(round(float(v) * 100))
                        except (ValueError, TypeError):
                            d[target] = None
                    else:
                        d[target] = v
        d["raw_json"] = json.dumps(raw, ensure_ascii=False, default=str)
        # v2.70: для composite-key таблиць (ms_demand_positions) primary key —
        # (demand_id, position_idx). Пропускаємо рядок тільки якщо нема ЖОДНОГО
        # з identifying полів.
        has_id = bool(d.get("id"))
        has_composite = bool(d.get("demand_id") is not None and d.get("position_idx") is not None)
        if not has_id and not has_composite: continue
        out.append(d)
    return out


def post_batch(worker_url: str, sync_key: str, entity: str, rows: list) -> dict:
    url = f"{worker_url.rstrip('/')}/api/dashboard/ingest"
    payload = {"entity": entity, "rows": rows}
    r = requests.post(
        url,
        json=payload,
        headers={"X-Sync-Key": sync_key, "Origin": "https://dreamcarua.github.io"},
        timeout=60,
    )
    if not r.ok:
        # КРИТИЧНО: лог body Worker'а перед raise, інакше неможливо діагностувати 500.
        try:
            body = r.text[:1500]
        except Exception:
            body = "<unreadable>"
        sample_keys = list((rows[0] if rows else {}).keys())
        sample_preview = json.dumps(rows[0] if rows else None, ensure_ascii=False, default=str)[:800]
        print(f"\n❌ post_batch {entity} rows={len(rows)} → HTTP {r.status_code}", file=sys.stderr, flush=True)
        print(f"   response body: {body}", file=sys.stderr, flush=True)
        print(f"   sample row keys: {sample_keys}", file=sys.stderr, flush=True)
        print(f"   sample row preview: {sample_preview}", file=sys.stderr, flush=True)
    r.raise_for_status()
    return r.json()


def post_sync_log(worker_url: str, sync_key: str, log: dict) -> dict:
    url = f"{worker_url.rstrip('/')}/api/dashboard/ingest"
    r = requests.post(
        url,
        json={"sync_log": log},
        headers={"X-Sync-Key": sync_key, "Origin": "https://dreamcarua.github.io"},
        timeout=15,
    )
    if not r.ok:
        try: print(f"❌ sync_log → HTTP {r.status_code}: {r.text[:500]}", file=sys.stderr, flush=True)
        except: pass
    r.raise_for_status()
    return r.json()


def ingest_entity(worker_url: str, sync_key: str, entity: str, df: pd.DataFrame, col_map: dict) -> int:
    rows = df_to_rows(df, col_map)
    total = len(rows)
    if total == 0:
        return 0
    sent = 0
    for i in range(0, total, BATCH_SIZE):
        batch = rows[i:i + BATCH_SIZE]
        resp = post_batch(worker_url, sync_key, entity, batch)
        sent += resp.get("inserted", len(batch))
    return sent


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", default=os.getenv("DATA_DIR", "./data"),
                        help="dir with xlsx files (default ./data)")
    parser.add_argument("--worker", default=os.getenv("WORKER_URL", ""),
                        help="Worker URL (or set WORKER_URL)")
    parser.add_argument("--key", default=os.getenv("SYNC_API_KEY", ""),
                        help="Sync API key (or set SYNC_API_KEY)")
    parser.add_argument("--trigger", default="manual", choices=["manual", "cron", "webhook"])
    parser.add_argument("--window-days", type=int, default=30)
    args = parser.parse_args()

    if not args.worker or not args.key:
        print("❌ WORKER_URL and SYNC_API_KEY required (env or --worker / --key)")
        sys.exit(2)

    data_dir = Path(args.data_dir).expanduser().resolve()
    if not data_dir.is_dir():
        print(f"❌ Data dir not found: {data_dir}")
        sys.exit(2)

    started = int(time.time())
    started_iso = datetime.now(timezone.utc).isoformat()
    print(f"🚀 D1 ingest started · {started_iso} · dir={data_dir}")

    entities_summary = {}
    errors = []

    for entity, spec in ENTITY_MAP.items():
        f = data_dir / spec["file"]
        if not f.exists():
            print(f"  ⚠️  {entity}: {spec['file']} not found, skipping")
            entities_summary[entity] = 0
            continue
        try:
            df = pd.read_excel(f, dtype=object)
            count = ingest_entity(args.worker, args.key, entity, df, spec["cols"])
            entities_summary[entity] = count
            print(f"  ✅ {entity:18s} → D1: {count} rows")
        except Exception as e:
            err = f"{entity}: {type(e).__name__}: {str(e)[:200]}"
            errors.append(err)
            print(f"  ❌ {entity}: {err}")
            traceback.print_exc()

    finished = int(time.time())
    duration = (finished - started) * 1000
    status = "success" if not errors else ("partial" if entities_summary else "failed")

    # Post sync_log
    try:
        post_sync_log(args.worker, args.key, {
            "started_at": started,
            "finished_at": finished,
            "status": status,
            "trigger": args.trigger,
            "entities": entities_summary,
            "errors": errors or None,
            "duration_ms": duration,
            "data_window_from": (datetime.now(timezone.utc) - __import__('datetime').timedelta(days=args.window_days)).isoformat(),
            "data_window_to": datetime.now(timezone.utc).isoformat(),
        })
        print(f"📝 sync_log written · status={status}")
    except Exception as e:
        print(f"⚠️  failed to write sync_log: {e}")

    total = sum(entities_summary.values())
    print(f"\n🎯 Done · {total} rows total · {len(errors)} errors · {duration / 1000:.1f}s")
    sys.exit(0 if status == "success" else 1)


if __name__ == "__main__":
    main()
